// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import ChatController from "./chat_controller"
application.register("chat", ChatController)

import HeaderController from "./header_controller"
application.register("header", HeaderController)

import ResetFormController from "./reset_form_controller"
application.register("reset-form", ResetFormController)
